net:
   bindIp: 0.0.0.0
   port: 27017


systemLog:
   destination: file
   path: "/var/log/mongodb/mongod.log"
   logAppend: true
   logRotate: rename


replication:
   replSetName: rs0
   # avoid cache presure on PSA architecture
   enableMajorityReadConcern: false

# enable if wanting to inspect data from arbiter
# setParameter:
#    enableLocalhostAuthBypass: false